#
# Pure Fusion API
# Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status ""Pending"" or ""Running"". You can poll (GET) the operation to check its status, waiting for it to change to ""Succeeded"" or ""Failed"". 
# Version: 1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

(Provider)

.PARAMETER Name
The name of the resource, supplied by the user at creation, and used in the URI path of a resource.
.PARAMETER DisplayName
The display name of the resource.
.PARAMETER ApartmentId
Apartment Identifier of Array. Return value of purearray list
.PARAMETER HostName
The host name of the array.
.PARAMETER HardwareType
Name of the hardware type
.PARAMETER ApplianceId
The Appliance id of the array.
.OUTPUTS

ArrayPost<PSCustomObject>
#>

function Initialize-PSFArrayPost {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ApartmentId},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HostName},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${HardwareType},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${ApplianceId}
    )

    Process {
        'Creating PSCustomObject: PSFusion => PSFArrayPost' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $HostName) {
            throw "invalid value for 'HostName', 'HostName' cannot be null."
        }

        if ($null -eq $HardwareType) {
            throw "invalid value for 'HardwareType', 'HardwareType' cannot be null."
        }

        if ($null -eq $ApplianceId) {
            throw "invalid value for 'ApplianceId', 'ApplianceId' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "display_name" = ${DisplayName}
            "apartment_id" = ${ApartmentId}
            "host_name" = ${HostName}
            "hardware_type" = ${HardwareType}
            "appliance_id" = ${ApplianceId}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to ArrayPost<PSCustomObject>

.DESCRIPTION

Convert from JSON to ArrayPost<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

ArrayPost<PSCustomObject>
#>
function ConvertFrom-PSFJsonToArrayPost {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSFusion => PSFArrayPost' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSFArrayPost
        $AllProperties = ("name", "display_name", "apartment_id", "host_name", "hardware_type", "appliance_id")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'name' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "host_name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'host_name' missing."
        } else {
            $HostName = $JsonParameters.PSobject.Properties["host_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "hardware_type"))) {
            throw "Error! JSON cannot be serialized due to the required property 'hardware_type' missing."
        } else {
            $HardwareType = $JsonParameters.PSobject.Properties["hardware_type"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "appliance_id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'appliance_id' missing."
        } else {
            $ApplianceId = $JsonParameters.PSobject.Properties["appliance_id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "display_name"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["display_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "apartment_id"))) { #optional property not found
            $ApartmentId = $null
        } else {
            $ApartmentId = $JsonParameters.PSobject.Properties["apartment_id"].value
        }

        $PSO = [PSCustomObject]@{
            "name" = ${Name}
            "display_name" = ${DisplayName}
            "apartment_id" = ${ApartmentId}
            "host_name" = ${HostName}
            "hardware_type" = ${HardwareType}
            "appliance_id" = ${ApplianceId}
        }

        return $PSO
    }

}

