#
# Pure Fusion API
# Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status ""Pending"" or ""Running"". You can poll (GET) the operation to check its status, waiting for it to change to ""Succeeded"" or ""Failed"". 
# Version: 1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Iqn
No description available.
.PARAMETER Personality
No description available.
.OUTPUTS

HostAccessPolicyAllOf<PSCustomObject>
#>

function Initialize-PSFHostAccessPolicyAllOf {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Iqn},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Personality}
    )

    Process {
        'Creating PSCustomObject: PSFusion => PSFHostAccessPolicyAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Iqn) {
            throw "invalid value for 'Iqn', 'Iqn' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "iqn" = ${Iqn}
            "personality" = ${Personality}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to HostAccessPolicyAllOf<PSCustomObject>

.DESCRIPTION

Convert from JSON to HostAccessPolicyAllOf<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

HostAccessPolicyAllOf<PSCustomObject>
#>
function ConvertFrom-PSFJsonToHostAccessPolicyAllOf {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSFusion => PSFHostAccessPolicyAllOf' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSFHostAccessPolicyAllOf
        $AllProperties = ("iqn", "personality")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'iqn' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "iqn"))) {
            throw "Error! JSON cannot be serialized due to the required property 'iqn' missing."
        } else {
            $Iqn = $JsonParameters.PSobject.Properties["iqn"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "personality"))) { #optional property not found
            $Personality = $null
        } else {
            $Personality = $JsonParameters.PSobject.Properties["personality"].value
        }

        $PSO = [PSCustomObject]@{
            "iqn" = ${Iqn}
            "personality" = ${Personality}
        }

        return $PSO
    }

}

