#
# Pure Fusion API
# Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status ""Pending"" or ""Running"". You can poll (GET) the operation to check its status, waiting for it to change to ""Succeeded"" or ""Failed"". 
# Version: 1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

Enum PlacementEngine.

.DESCRIPTION

Policy engine used for determining Placements. If not specified, the default is ""pure1meta"". Pure1 Meta recommendations might take a few minutes to process.
#>

enum PlacementEngine {
    # enum value: "pure1meta"
    pure1meta
    # enum value: "heuristics"
    heuristics
}

