#
# Pure Fusion API
# Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status ""Pending"" or ""Running"". You can poll (GET) the operation to check its status, waiting for it to change to ""Succeeded"" or ""Failed"". 
# Version: 1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Avg
No description available.
.PARAMETER BlendedMax
No description available.
.OUTPUTS

Pure1MetaPlacementRecommendationLoadValues<PSCustomObject>
#>

function Initialize-PSFPure1MetaPlacementRecommendationLoadValues {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${Avg},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject[]]
        ${BlendedMax}
    )

    Process {
        'Creating PSCustomObject: PSFusion => PSFPure1MetaPlacementRecommendationLoadValues' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug


        $PSO = [PSCustomObject]@{
            "avg" = ${Avg}
            "blended_max" = ${BlendedMax}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to Pure1MetaPlacementRecommendationLoadValues<PSCustomObject>

.DESCRIPTION

Convert from JSON to Pure1MetaPlacementRecommendationLoadValues<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

Pure1MetaPlacementRecommendationLoadValues<PSCustomObject>
#>
function ConvertFrom-PSFJsonToPure1MetaPlacementRecommendationLoadValues {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSFusion => PSFPure1MetaPlacementRecommendationLoadValues' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSFPure1MetaPlacementRecommendationLoadValues
        $AllProperties = ("avg", "blended_max")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "avg"))) { #optional property not found
            $Avg = $null
        } else {
            $Avg = $JsonParameters.PSobject.Properties["avg"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "blended_max"))) { #optional property not found
            $BlendedMax = $null
        } else {
            $BlendedMax = $JsonParameters.PSobject.Properties["blended_max"].value
        }

        $PSO = [PSCustomObject]@{
            "avg" = ${Avg}
            "blended_max" = ${BlendedMax}
        }

        return $PSO
    }

}

