#
# Pure Fusion API
# Pure Fusion is fully API-driven. Most APIs which change the system (POST, PATCH, DELETE) return an Operation in status ""Pending"" or ""Running"". You can poll (GET) the operation to check its status, waiting for it to change to ""Succeeded"" or ""Failed"". 
# Version: 1.1
# Generated by OpenAPI Generator: https://openapi-generator.tech
#

<#
.SYNOPSIS

No summary available.

.DESCRIPTION

No description available.

.PARAMETER Id
An immutable, globally unique, system generated identifier.
.PARAMETER Name
The name of the resource, supplied by the user at creation, and used in the URI path of a resource.
.PARAMETER SelfLink
The URI of the resource.
.PARAMETER DisplayName
The display name of the resource.
.PARAMETER StorageService
No description available.
.PARAMETER SizeLimit
The maximum size allowed
.PARAMETER IopsLimit
The maximum IOPS allowed
.PARAMETER BandwidthLimit
The maximum bandwidth allowed
.OUTPUTS

StorageClass<PSCustomObject>
#>

function Initialize-PSFStorageClass {
    [CmdletBinding()]
    Param (
        [Parameter(Position = 0, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Id},
        [Parameter(Position = 1, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${Name},
        [Parameter(Position = 2, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${SelfLink},
        [Parameter(Position = 3, ValueFromPipelineByPropertyName = $true)]
        [String]
        ${DisplayName},
        [Parameter(Position = 4, ValueFromPipelineByPropertyName = $true)]
        [PSCustomObject]
        ${StorageService},
        [Parameter(Position = 5, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${SizeLimit},
        [Parameter(Position = 6, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${IopsLimit},
        [Parameter(Position = 7, ValueFromPipelineByPropertyName = $true)]
        [Int64]
        ${BandwidthLimit}
    )

    Process {
        'Creating PSCustomObject: PSFusion => PSFStorageClass' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        if ($null -eq $Id) {
            throw "invalid value for 'Id', 'Id' cannot be null."
        }

        if ($null -eq $Name) {
            throw "invalid value for 'Name', 'Name' cannot be null."
        }

        if ($null -eq $SelfLink) {
            throw "invalid value for 'SelfLink', 'SelfLink' cannot be null."
        }

        if ($null -eq $SizeLimit) {
            throw "invalid value for 'SizeLimit', 'SizeLimit' cannot be null."
        }

        if ($null -eq $IopsLimit) {
            throw "invalid value for 'IopsLimit', 'IopsLimit' cannot be null."
        }

        if ($null -eq $BandwidthLimit) {
            throw "invalid value for 'BandwidthLimit', 'BandwidthLimit' cannot be null."
        }


        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "self_link" = ${SelfLink}
            "display_name" = ${DisplayName}
            "storage_service" = ${StorageService}
            "size_limit" = ${SizeLimit}
            "iops_limit" = ${IopsLimit}
            "bandwidth_limit" = ${BandwidthLimit}
        }


        return $PSO
    }
}

<#
.SYNOPSIS

Convert from JSON to StorageClass<PSCustomObject>

.DESCRIPTION

Convert from JSON to StorageClass<PSCustomObject>

.PARAMETER Json

Json object

.OUTPUTS

StorageClass<PSCustomObject>
#>
function ConvertFrom-PSFJsonToStorageClass {
    Param(
        [AllowEmptyString()]
        [string]$Json
    )

    Process {
        'Converting JSON to PSCustomObject: PSFusion => PSFStorageClass' | Write-Debug
        $PSBoundParameters | Out-DebugParameter | Write-Debug

        $JsonParameters = ConvertFrom-Json -InputObject $Json

        # check if Json contains properties not defined in PSFStorageClass
        $AllProperties = ("id", "name", "self_link", "display_name", "storage_service", "size_limit", "iops_limit", "bandwidth_limit")
        foreach ($name in $JsonParameters.PsObject.Properties.Name) {
            if (!($AllProperties.Contains($name))) {
                throw "Error! JSON key '$name' not found in the properties: $($AllProperties)"
            }
        }

        If ([string]::IsNullOrEmpty($Json) -or $Json -eq "{}") { # empty json
            throw "Error! Empty JSON cannot be serialized due to the required property 'id' missing."
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "id"))) {
            throw "Error! JSON cannot be serialized due to the required property 'id' missing."
        } else {
            $Id = $JsonParameters.PSobject.Properties["id"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "name"))) {
            throw "Error! JSON cannot be serialized due to the required property 'name' missing."
        } else {
            $Name = $JsonParameters.PSobject.Properties["name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "self_link"))) {
            throw "Error! JSON cannot be serialized due to the required property 'self_link' missing."
        } else {
            $SelfLink = $JsonParameters.PSobject.Properties["self_link"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "size_limit"))) {
            throw "Error! JSON cannot be serialized due to the required property 'size_limit' missing."
        } else {
            $SizeLimit = $JsonParameters.PSobject.Properties["size_limit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "iops_limit"))) {
            throw "Error! JSON cannot be serialized due to the required property 'iops_limit' missing."
        } else {
            $IopsLimit = $JsonParameters.PSobject.Properties["iops_limit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "bandwidth_limit"))) {
            throw "Error! JSON cannot be serialized due to the required property 'bandwidth_limit' missing."
        } else {
            $BandwidthLimit = $JsonParameters.PSobject.Properties["bandwidth_limit"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "display_name"))) { #optional property not found
            $DisplayName = $null
        } else {
            $DisplayName = $JsonParameters.PSobject.Properties["display_name"].value
        }

        if (!([bool]($JsonParameters.PSobject.Properties.name -match "storage_service"))) { #optional property not found
            $StorageService = $null
        } else {
            $StorageService = $JsonParameters.PSobject.Properties["storage_service"].value
        }

        $PSO = [PSCustomObject]@{
            "id" = ${Id}
            "name" = ${Name}
            "self_link" = ${SelfLink}
            "display_name" = ${DisplayName}
            "storage_service" = ${StorageService}
            "size_limit" = ${SizeLimit}
            "iops_limit" = ${IopsLimit}
            "bandwidth_limit" = ${BandwidthLimit}
        }

        return $PSO
    }

}

